name: Violation Search

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This adds the manual trigger option
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 PM UTC (6:00 AM Central Time)
    - cron: '0 19 * * *'  # Runs at 7:00 PM UTC (1:00 PM Central Time)

jobs:
  search:
    runs-on: ubuntu-latest

    environment: login  # Specify the environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run Violation Search
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ViolationSearch.py

      - name: Debug Git status
        run: |
          git status
          git log -1

      - name: Stage changes
        run: git add violation_search_feed.xml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m 'Update RSS feed' || echo "No changes to commit"
          git pull --rebase  # Pull the latest changes
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
