name: Violation Search

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This adds the manual trigger option

jobs:
  search:
    runs-on: ubuntu-latest

    environment: login  # Specify the environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Clone private repository
        run: |
          git clone https://cOdES2424:${{ secrets.PAT }}@github.com/cOdES2424/Secure.git
        env:
          PAT: ${{ secrets.PAT }}

      - name: Set up environment variable
        run: echo "CSV_FILE_PATH=Secure/cases.csv" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run Violation Search
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ViolationSearch.py

      - name: Debug Git status
        run: |
          git status
          git log -1

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git rm --cached -r Secure  # Remove Secure directory from index
          git add violation_search_feed.xml
          git commit -m 'Update RSS feed' || echo "No changes to commit"
          git stash  # Stash changes
          git pull --rebase  # Pull the latest changes
          git stash pop  # Apply the stashed changes
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
