name: Generate Violation Search RSS Feed

on:
  schedule:
    - cron: '30 13 * * *' # Runs at 7:30 AM Central Time
    - cron: '0 19 * * *'  # Runs at 1:00 PM Central Time
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ' --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add violation_search_feed.xml
        git commit -m 'Update RSS feed'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
